# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4vV4-XQ5v-p-hWyvnjoNcZCIsTDr57i
"""

# ── CELLULE 1 : Installations & Imports ──────────────────────

!pip install scikit-learn pandas numpy matplotlib seaborn -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import matplotlib.patheffects as pe
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics import (classification_report, confusion_matrix,
                             roc_auc_score, roc_curve, precision_recall_curve,
                             average_precision_score)
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.inspection import permutation_importance
import warnings
warnings.filterwarnings('ignore')

# Palette corporative
DARK_BG    = "#0D1117"
CARD_BG    = "#161B22"
ACCENT_RED = "#E63946"
ACCENT_YLW = "#F4A261"
ACCENT_GRN = "#2EC4B6"
ACCENT_BLU = "#457B9D"
TEXT_MAIN  = "#E6EDF3"
TEXT_SUB   = "#8B949E"

print("✅  Imports réussis — prêt pour l'analyse !")

# ── CELLULE 2 : Création du Dataset ──────────────────────────

np.random.seed(42)
n_employes = 1000

data = {
    'ID_Employe': range(1, n_employes + 1),
    'Departement': np.random.choice(
        ['Achats', 'Finance', 'Ventes', 'RH', 'IT', 'Logistique'],
        n_employes, p=[0.15, 0.15, 0.25, 0.10, 0.15, 0.20]
    ),
    'Anciennete_Annees':        np.random.randint(1, 25, n_employes),
    'Score_Pression_Financiere': np.random.randint(1, 11, n_employes),
    'Satisfaction_Travail':      np.random.randint(1, 11, n_employes),
    'Heures_Supp_Mois':          np.random.randint(0, 50, n_employes),
    'Conges_Non_Pris':           np.random.randint(0, 30, n_employes),
    'Acces_Privilegie':          np.random.choice([0, 1], n_employes, p=[0.8, 0.2])
}
df = pd.DataFrame(data)

# Variable cible — Triangle de Cressey
score_risque = (
    (df['Score_Pression_Financiere'] * 0.4) +
    (df['Acces_Privilegie'] * 15) +
    ((10 - df['Satisfaction_Travail']) * 0.3) +
    (df['Anciennete_Annees'] * 0.2)
)
seuil = np.percentile(score_risque, 95)
df['Fraude_Interne'] = (score_risque >= seuil).astype(int)
df['Score_Risque']   = score_risque

# Encodage département
le = LabelEncoder()
df['Dept_encoded'] = le.fit_transform(df['Departement'])

print(f"📊  Dataset : {len(df)} employés | {df['Fraude_Interne'].sum()} cas de fraude ({df['Fraude_Interne'].mean()*100:.1f} %)")
df.head()

# ── CELLULE 3 : Figure 1 — Vue d'ensemble & Triangle de Cressey ──

fig = plt.figure(figsize=(20, 12), facecolor=DARK_BG)
fig.suptitle("PRÉDICTION DE LA FRAUDE INTERNE EN ENTREPRISE",
             fontsize=22, fontweight='bold', color=TEXT_MAIN, y=0.98)
fig.text(0.5, 0.94, "Basé sur le Triangle de la Fraude — ACFE Report 2024",
         ha='center', fontsize=13, color=TEXT_SUB)

gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35,
                       left=0.06, right=0.97, top=0.91, bottom=0.07)

# ── KPI Cards ────────────────────────────────────────────────
ax_kpi = fig.add_subplot(gs[0, :])
ax_kpi.set_xlim(0, 10); ax_kpi.set_ylim(0, 1); ax_kpi.axis('off')

kpis = [
    ("👥", "Effectif Total",   f"{len(df):,}", ACCENT_BLU),
    ("🚨", "Cas de Fraude",    f"{df['Fraude_Interne'].sum()}", ACCENT_RED),
    ("📈", "Taux de Fraude",   f"{df['Fraude_Interne'].mean()*100:.1f}%", ACCENT_YLW),
    ("🔑", "Accès Privilégié", f"{df['Acces_Privilegie'].mean()*100:.0f}%", ACCENT_GRN),
    ("😟", "Pression Moy.",    f"{df['Score_Pression_Financiere'].mean():.1f}/10", "#C77DFF"),
]
for i, (icon, label, val, col) in enumerate(kpis):
    x = 0.5 + i * 1.85
    rect = FancyBboxPatch((x - 0.82, 0.05), 1.6, 0.88,
                          boxstyle="round,pad=0.05", facecolor=CARD_BG,
                          edgecolor=col, linewidth=2)
    ax_kpi.add_patch(rect)
    ax_kpi.text(x, 0.74, icon,   ha='center', va='center', fontsize=22)
    ax_kpi.text(x, 0.50, val,    ha='center', va='center', fontsize=20,
                fontweight='bold', color=col)
    ax_kpi.text(x, 0.22, label,  ha='center', va='center', fontsize=10,
                color=TEXT_SUB)

# ── Triangle de Cressey ──────────────────────────────────────
ax_tri = fig.add_subplot(gs[1, 0])
ax_tri.set_xlim(0, 10); ax_tri.set_ylim(0, 10); ax_tri.axis('off')
ax_tri.set_facecolor(DARK_BG)
ax_tri.set_title("🔺 Triangle de la Fraude\n(Cressey, 1953)", color=TEXT_MAIN,
                 fontsize=12, fontweight='bold', pad=10)

triangle_pts = np.array([[5, 9], [1, 2], [9, 2], [5, 9]])
ax_tri.fill(triangle_pts[:, 0], triangle_pts[:, 1],
            alpha=0.15, color=ACCENT_RED)
ax_tri.plot(triangle_pts[:, 0], triangle_pts[:, 1],
            color=ACCENT_RED, linewidth=2.5)

nodes = [
    (5, 9.3, "OPPORTUNITÉ",   "Accès Privilégié\nContrôles Faibles", ACCENT_GRN),
    (0.3, 1.2, "PRESSION",    "Stress Financier\nObjectifs Irréalistes", ACCENT_YLW),
    (9.7, 1.2, "RATIONALISATION", "Insatisfaction\nSentiment d'Injustice", "#C77DFF"),
]
for xn, yn, title, sub, col in nodes:
    ax_tri.text(xn, yn, title, ha='center', va='bottom', fontsize=9,
                fontweight='bold', color=col)
    ax_tri.text(xn, yn - 0.9, sub, ha='center', va='top', fontsize=7.5,
                color=TEXT_SUB, linespacing=1.4)

ax_tri.text(5, 5.3, "FRAUDE\nINTERNE", ha='center', va='center',
            fontsize=13, fontweight='bold', color=ACCENT_RED, alpha=0.9)

# ── Fraude par département ───────────────────────────────────
ax_dept = fig.add_subplot(gs[1, 1])
ax_dept.set_facecolor(DARK_BG)
dept_stats = df.groupby('Departement').agg(
    total=('Fraude_Interne', 'count'),
    fraudes=('Fraude_Interne', 'sum')
).assign(taux=lambda x: x['fraudes'] / x['total'] * 100).sort_values('taux', ascending=True)

colors_bar = [ACCENT_RED if v > dept_stats['taux'].mean() else ACCENT_BLU
              for v in dept_stats['taux']]
bars = ax_dept.barh(dept_stats.index, dept_stats['taux'],
                    color=colors_bar, edgecolor='none', height=0.6)
for bar, v in zip(bars, dept_stats['taux']):
    ax_dept.text(v + 0.2, bar.get_y() + bar.get_height()/2,
                 f'{v:.1f}%', va='center', fontsize=9, color=TEXT_MAIN)
ax_dept.axvline(dept_stats['taux'].mean(), color=ACCENT_YLW,
                linestyle='--', linewidth=1.5, alpha=0.8)
ax_dept.set_title("Taux de Fraude par Département", color=TEXT_MAIN,
                  fontsize=11, fontweight='bold')
ax_dept.set_xlabel("Taux de fraude (%)", color=TEXT_SUB, fontsize=9)
ax_dept.tick_params(colors=TEXT_SUB, labelsize=9)
for spine in ax_dept.spines.values(): spine.set_visible(False)
ax_dept.set_facecolor(DARK_BG)
ax_dept.xaxis.label.set_color(TEXT_SUB)

# ── Distribution du score de risque ─────────────────────────
ax_dist = fig.add_subplot(gs[1, 2])
ax_dist.set_facecolor(DARK_BG)
non_fraud = df[df['Fraude_Interne'] == 0]['Score_Risque']
fraud     = df[df['Fraude_Interne'] == 1]['Score_Risque']
ax_dist.hist(non_fraud, bins=35, color=ACCENT_BLU, alpha=0.7,
             label='Non-Fraudeur', density=True, edgecolor='none')
ax_dist.hist(fraud, bins=20, color=ACCENT_RED, alpha=0.8,
             label='Fraudeur', density=True, edgecolor='none')
ax_dist.axvline(seuil, color=ACCENT_YLW, linestyle='--',
                linewidth=1.8, label=f'Seuil = {seuil:.1f}')
ax_dist.set_title("Distribution du Score de Risque", color=TEXT_MAIN,
                  fontsize=11, fontweight='bold')
ax_dist.set_xlabel("Score de risque", color=TEXT_SUB, fontsize=9)
ax_dist.set_ylabel("Densité", color=TEXT_SUB, fontsize=9)
ax_dist.legend(fontsize=8, facecolor=CARD_BG, labelcolor=TEXT_MAIN,
               edgecolor='none')
ax_dist.tick_params(colors=TEXT_SUB, labelsize=9)
for spine in ax_dist.spines.values(): spine.set_visible(False)

plt.savefig('fig1_overview.png', dpi=150, bbox_inches='tight',
            facecolor=DARK_BG)
plt.show()
print("✅  Figure 1 enregistrée")

# ── CELLULE 4 : Figure 2 — Analyse exploratoire ──────────────

fig, axes = plt.subplots(2, 3, figsize=(20, 11), facecolor=DARK_BG)
fig.suptitle("ANALYSE EXPLORATOIRE — PROFILS À RISQUE",
             fontsize=18, fontweight='bold', color=TEXT_MAIN, y=1.01)

palette = {0: ACCENT_BLU, 1: ACCENT_RED}
labels  = {0: "Non-Fraudeur", 1: "Fraudeur"}

# 1. Pression financière vs Satisfaction (scatter)
ax = axes[0, 0]; ax.set_facecolor(DARK_BG)
for fraud_val, col in palette.items():
    sub = df[df['Fraude_Interne'] == fraud_val]
    ax.scatter(sub['Score_Pression_Financiere'],
               sub['Satisfaction_Travail'],
               c=col, alpha=0.5, s=18, label=labels[fraud_val], edgecolors='none')
ax.set_title("Pression vs Satisfaction", color=TEXT_MAIN, fontweight='bold')
ax.set_xlabel("Pression Financière", color=TEXT_SUB)
ax.set_ylabel("Satisfaction au Travail", color=TEXT_SUB)
ax.legend(facecolor=CARD_BG, labelcolor=TEXT_MAIN, edgecolor='none', fontsize=9)
ax.tick_params(colors=TEXT_SUB)
for sp in ax.spines.values(): sp.set_visible(False)

# 2. Ancienneté — boxplot
ax = axes[0, 1]; ax.set_facecolor(DARK_BG)
data_box = [df[df['Fraude_Interne'] == 0]['Anciennete_Annees'],
            df[df['Fraude_Interne'] == 1]['Anciennete_Annees']]
bp = ax.boxplot(data_box, patch_artist=True, widths=0.5,
                medianprops=dict(color=ACCENT_YLW, linewidth=2))
for patch, col in zip(bp['boxes'], [ACCENT_BLU, ACCENT_RED]):
    patch.set_facecolor(col); patch.set_alpha(0.7)
for element in ['whiskers', 'caps', 'fliers']:
    for item in bp[element]: item.set_color(TEXT_SUB)
ax.set_xticklabels(['Non-Fraudeur', 'Fraudeur'], color=TEXT_MAIN)
ax.set_title("Ancienneté par Profil", color=TEXT_MAIN, fontweight='bold')
ax.set_ylabel("Années", color=TEXT_SUB)
ax.tick_params(colors=TEXT_SUB)
for sp in ax.spines.values(): sp.set_visible(False)

# 3. Heures supplémentaires
ax = axes[0, 2]; ax.set_facecolor(DARK_BG)
for fraud_val, col in palette.items():
    sub = df[df['Fraude_Interne'] == fraud_val]
    ax.hist(sub['Heures_Supp_Mois'], bins=25, color=col, alpha=0.7,
            density=True, label=labels[fraud_val], edgecolor='none')
ax.set_title("Heures Supplémentaires / Mois", color=TEXT_MAIN, fontweight='bold')
ax.set_xlabel("Heures", color=TEXT_SUB)
ax.set_ylabel("Densité", color=TEXT_SUB)
ax.legend(facecolor=CARD_BG, labelcolor=TEXT_MAIN, edgecolor='none', fontsize=9)
ax.tick_params(colors=TEXT_SUB)
for sp in ax.spines.values(): sp.set_visible(False)

# 4. Congés non pris — violin
ax = axes[1, 0]; ax.set_facecolor(DARK_BG)
parts = ax.violinplot(
    [df[df['Fraude_Interne'] == 0]['Conges_Non_Pris'],
     df[df['Fraude_Interne'] == 1]['Conges_Non_Pris']],
    positions=[1, 2], showmedians=True
)
for pc, col in zip(parts['bodies'], [ACCENT_BLU, ACCENT_RED]):
    pc.set_facecolor(col); pc.set_alpha(0.7)
parts['cmedians'].set_color(ACCENT_YLW)
parts['cbars'].set_color(TEXT_SUB)
parts['cmins'].set_color(TEXT_SUB)
parts['cmaxes'].set_color(TEXT_SUB)
ax.set_xticks([1, 2]); ax.set_xticklabels(['Non-Fraudeur', 'Fraudeur'], color=TEXT_MAIN)
ax.set_title("Congés Non Pris", color=TEXT_MAIN, fontweight='bold')
ax.set_ylabel("Jours", color=TEXT_SUB)
ax.tick_params(colors=TEXT_SUB)
for sp in ax.spines.values(): sp.set_visible(False)

# 5. Heatmap corrélations
ax = axes[1, 1]; ax.set_facecolor(DARK_BG)
num_cols = ['Score_Pression_Financiere', 'Satisfaction_Travail',
            'Heures_Supp_Mois', 'Conges_Non_Pris',
            'Anciennete_Annees', 'Acces_Privilegie', 'Fraude_Interne']
corr = df[num_cols].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
cmap = sns.diverging_palette(220, 20, as_cmap=True)
sns.heatmap(corr, mask=mask, cmap=cmap, center=0, ax=ax,
            annot=True, fmt='.2f', annot_kws={'size': 8, 'color': TEXT_MAIN},
            linewidths=0.5, linecolor=DARK_BG,
            cbar_kws={'shrink': 0.8})
ax.set_title("Matrice de Corrélation", color=TEXT_MAIN, fontweight='bold')
ax.tick_params(colors=TEXT_SUB, labelsize=8)
short_names = ['Pression', 'Satisfaction', 'H.Supp', 'Congés', 'Ancienneté', 'Accès Priv.', 'Fraude']
ax.set_xticklabels(short_names, rotation=40, ha='right', color=TEXT_SUB, fontsize=8)
ax.set_yticklabels(short_names, rotation=0, color=TEXT_SUB, fontsize=8)

# 6. Accès privilégié vs fraude
ax = axes[1, 2]; ax.set_facecolor(DARK_BG)
ct = pd.crosstab(df['Acces_Privilegie'], df['Fraude_Interne'], normalize='index') * 100
x = np.arange(2)
bars1 = ax.bar(x - 0.2, ct[0], 0.38, label='Non-Fraudeur', color=ACCENT_BLU, alpha=0.85)
bars2 = ax.bar(x + 0.2, ct[1], 0.38, label='Fraudeur',     color=ACCENT_RED, alpha=0.85)
for bar in list(bars1) + list(bars2):
    h = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2, h + 1,
            f'{h:.1f}%', ha='center', va='bottom', fontsize=9, color=TEXT_MAIN)
ax.set_xticks(x)
ax.set_xticklabels(['Sans accès privilégié', 'Avec accès privilégié'],
                   color=TEXT_MAIN, fontsize=9)
ax.set_title("Impact de l'Accès Privilégié", color=TEXT_MAIN, fontweight='bold')
ax.set_ylabel("Part (%)", color=TEXT_SUB)
ax.legend(facecolor=CARD_BG, labelcolor=TEXT_MAIN, edgecolor='none', fontsize=9)
ax.tick_params(colors=TEXT_SUB)
for sp in ax.spines.values(): sp.set_visible(False)

plt.tight_layout()
plt.savefig('fig2_eda.png', dpi=150, bbox_inches='tight', facecolor=DARK_BG)
plt.show()
print("✅  Figure 2 enregistrée")

# ── CELLULE 5 : Entraînement des modèles ML ──────────────────

features = ['Dept_encoded', 'Anciennete_Annees', 'Score_Pression_Financiere',
            'Satisfaction_Travail', 'Heures_Supp_Mois', 'Conges_Non_Pris',
            'Acces_Privilegie']
feat_labels = ['Département', 'Ancienneté', 'Pression Financière',
               'Satisfaction', 'Heures Supp.', 'Congés Non Pris', 'Accès Privilégié']

X = df[features]; y = df['Fraude_Interne']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s  = scaler.transform(X_test)

# Random Forest
rf = RandomForestClassifier(n_estimators=200, max_depth=8, random_state=42,
                             class_weight='balanced', min_samples_leaf=3)
rf.fit(X_train, y_train)
y_prob_rf = rf.predict_proba(X_test)[:, 1]
y_pred_rf = rf.predict(X_test)

# Gradient Boosting
gb = GradientBoostingClassifier(n_estimators=150, learning_rate=0.08,
                                 max_depth=4, random_state=42)
gb.fit(X_train, y_train)
y_prob_gb = gb.predict_proba(X_test)[:, 1]
y_pred_gb = gb.predict(X_test)

# Régression Logistique
lr = LogisticRegression(random_state=42, class_weight='balanced',
                         max_iter=1000, C=0.5)
lr.fit(X_train_s, y_train)
y_prob_lr = lr.predict_proba(X_test_s)[:, 1]
y_pred_lr = lr.predict(X_test_s)

# Cross-validation AUC
cv  = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
auc_rf_cv = cross_val_score(rf, X, y, cv=cv, scoring='roc_auc').mean()
auc_gb_cv = cross_val_score(gb, X, y, cv=cv, scoring='roc_auc').mean()
auc_lr_cv = cross_val_score(lr, scaler.fit_transform(X), y,
                             cv=cv, scoring='roc_auc').mean()

models_perf = {
    'Random Forest':       (y_pred_rf, y_prob_rf, auc_rf_cv, ACCENT_GRN),
    'Gradient Boosting':   (y_pred_gb, y_prob_gb, auc_gb_cv, ACCENT_YLW),
    'Logistic Regression': (y_pred_lr, y_prob_lr, auc_lr_cv, ACCENT_BLU),
}
for name, (pred, prob, auc_cv, _) in models_perf.items():
    auc = roc_auc_score(y_test, prob)
    print(f"  {name:<25}  AUC test = {auc:.4f}  |  AUC CV-5 = {auc_cv:.4f}")

print("\n✅  Modèles entraînés !")

# ── CELLULE 6 : Figure 3 — Performances des modèles ─────────

fig = plt.figure(figsize=(20, 12), facecolor=DARK_BG)
fig.suptitle("PERFORMANCES DES MODÈLES DE CLASSIFICATION",
             fontsize=18, fontweight='bold', color=TEXT_MAIN, y=1.01)

gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.38)

# ── Courbes ROC ──────────────────────────────────────────────
ax_roc = fig.add_subplot(gs[0, 0])
ax_roc.set_facecolor(DARK_BG)
ax_roc.plot([0, 1], [0, 1], '--', color=TEXT_SUB, linewidth=1, alpha=0.5)
for name, (pred, prob, auc_cv, col) in models_perf.items():
    fpr, tpr, _ = roc_curve(y_test, prob)
    auc = roc_auc_score(y_test, prob)
    ax_roc.plot(fpr, tpr, color=col, linewidth=2.5, label=f"{name} (AUC={auc:.3f})")
ax_roc.fill_between(*roc_curve(y_test, y_prob_rf)[:2],
                    alpha=0.08, color=ACCENT_GRN)
ax_roc.set_title("Courbes ROC", color=TEXT_MAIN, fontweight='bold')
ax_roc.set_xlabel("Taux Faux Positifs", color=TEXT_SUB)
ax_roc.set_ylabel("Taux Vrais Positifs", color=TEXT_SUB)
ax_roc.legend(facecolor=CARD_BG, labelcolor=TEXT_MAIN,
               edgecolor='none', fontsize=8)
ax_roc.tick_params(colors=TEXT_SUB)
for sp in ax_roc.spines.values(): sp.set_visible(False)

# ── Précision-Rappel ─────────────────────────────────────────
ax_pr = fig.add_subplot(gs[0, 1])
ax_pr.set_facecolor(DARK_BG)
for name, (pred, prob, auc_cv, col) in models_perf.items():
    prec, rec, _ = precision_recall_curve(y_test, prob)
    ap = average_precision_score(y_test, prob)
    ax_pr.plot(rec, prec, color=col, linewidth=2.5, label=f"{name} (AP={ap:.3f})")
baseline = y_test.mean()
ax_pr.axhline(baseline, color=TEXT_SUB, linestyle='--',
              linewidth=1, alpha=0.6, label=f"Baseline ({baseline:.2f})")
ax_pr.set_title("Courbes Précision-Rappel", color=TEXT_MAIN, fontweight='bold')
ax_pr.set_xlabel("Rappel", color=TEXT_SUB)
ax_pr.set_ylabel("Précision", color=TEXT_SUB)
ax_pr.legend(facecolor=CARD_BG, labelcolor=TEXT_MAIN,
              edgecolor='none', fontsize=8)
ax_pr.tick_params(colors=TEXT_SUB)
for sp in ax_pr.spines.values(): sp.set_visible(False)

# ── Matrice de confusion RF ──────────────────────────────────
ax_cm = fig.add_subplot(gs[0, 2])
ax_cm.set_facecolor(DARK_BG)
cm = confusion_matrix(y_test, y_pred_rf)
cmap_cm = sns.light_palette(ACCENT_RED, as_cmap=True)
sns.heatmap(cm, annot=True, fmt='d', ax=ax_cm, cmap=cmap_cm,
            linewidths=2, linecolor=DARK_BG,
            xticklabels=['Prédit Non-Fraude', 'Prédit Fraude'],
            yticklabels=['Réel Non-Fraude', 'Réel Fraude'],
            annot_kws={'size': 16, 'weight': 'bold', 'color': TEXT_MAIN})
ax_cm.set_title("Matrice de Confusion (RF)", color=TEXT_MAIN, fontweight='bold')
ax_cm.tick_params(colors=TEXT_SUB, labelsize=9)

# ── Feature Importance ───────────────────────────────────────
ax_fi = fig.add_subplot(gs[1, 0])
ax_fi.set_facecolor(DARK_BG)
importances = rf.feature_importances_
idx = np.argsort(importances)
colors_fi = [ACCENT_RED if importances[i] == max(importances) else ACCENT_BLU
             for i in idx]
bars = ax_fi.barh([feat_labels[i] for i in idx], importances[idx],
                   color=colors_fi, edgecolor='none', height=0.6)
for bar, v in zip(bars, importances[idx]):
    ax_fi.text(v + 0.002, bar.get_y() + bar.get_height()/2,
               f'{v:.3f}', va='center', fontsize=8.5, color=TEXT_MAIN)
ax_fi.set_title("Importance des Variables (RF)", color=TEXT_MAIN, fontweight='bold')
ax_fi.set_xlabel("Importance (Gini)", color=TEXT_SUB)
ax_fi.tick_params(colors=TEXT_SUB, labelsize=9)
for sp in ax_fi.spines.values(): sp.set_visible(False)

# ── Comparatif AUC (cross-val) ───────────────────────────────
ax_auc = fig.add_subplot(gs[1, 1])
ax_auc.set_facecolor(DARK_BG)
noms   = ['Random Forest', 'Gradient\nBoosting', 'Logistic\nRegression']
aucs   = [auc_rf_cv, auc_gb_cv, auc_lr_cv]
cols_b = [ACCENT_GRN, ACCENT_YLW, ACCENT_BLU]
bars_auc = ax_auc.bar(noms, aucs, color=cols_b, edgecolor='none',
                       width=0.5, alpha=0.9)
for bar, v in zip(bars_auc, aucs):
    ax_auc.text(bar.get_x() + bar.get_width()/2, v + 0.003,
                f'{v:.4f}', ha='center', va='bottom',
                fontsize=11, fontweight='bold', color=TEXT_MAIN)
ax_auc.set_ylim(0.5, 1.05)
ax_auc.axhline(0.5, color=TEXT_SUB, linestyle='--', linewidth=1, alpha=0.5)
ax_auc.set_title("AUC — Validation Croisée (k=5)", color=TEXT_MAIN, fontweight='bold')
ax_auc.set_ylabel("Score AUC", color=TEXT_SUB)
ax_auc.tick_params(colors=TEXT_SUB, labelsize=9)
for sp in ax_auc.spines.values(): sp.set_visible(False)

# ── Rapport de classification (texte) ────────────────────────
ax_rep = fig.add_subplot(gs[1, 2])
ax_rep.set_facecolor(CARD_BG)
ax_rep.axis('off')
report = classification_report(y_test, y_pred_rf, target_names=['Non-Fraude', 'Fraude'])
ax_rep.text(0.05, 0.95, "Rapport — Random Forest", transform=ax_rep.transAxes,
            fontsize=11, fontweight='bold', color=ACCENT_GRN, va='top')
ax_rep.text(0.05, 0.78, report, transform=ax_rep.transAxes,
            fontsize=9.5, color=TEXT_MAIN, va='top', family='monospace',
            linespacing=1.6)
rect = FancyBboxPatch((0.02, 0.02), 0.96, 0.96,
                       boxstyle="round,pad=0.02",
                       facecolor='none', edgecolor=ACCENT_GRN,
                       linewidth=1.5, transform=ax_rep.transAxes)
ax_rep.add_patch(rect)

plt.savefig('fig3_models.png', dpi=150, bbox_inches='tight', facecolor=DARK_BG)
plt.show()
print("✅  Figure 3 enregistrée")

# ── CELLULE 7 : Figure 4 — Analyse du risque & Segmentation ──

fig, axes = plt.subplots(2, 2, figsize=(18, 12), facecolor=DARK_BG)
fig.suptitle("SEGMENTATION DES PROFILS À RISQUE",
             fontsize=18, fontweight='bold', color=TEXT_MAIN, y=1.01)

# Score de risque continu par département
ax = axes[0, 0]; ax.set_facecolor(DARK_BG)
dept_order = df.groupby('Departement')['Score_Risque'].mean().sort_values(ascending=False).index
data_vio = [df[df['Departement'] == d]['Score_Risque'].values for d in dept_order]
parts = ax.violinplot(data_vio, showmedians=True)
dept_colors = [ACCENT_RED, ACCENT_RED, ACCENT_YLW, ACCENT_YLW, ACCENT_BLU, ACCENT_BLU]
for pc, col in zip(parts['bodies'], dept_colors):
    pc.set_facecolor(col); pc.set_alpha(0.65)
parts['cmedians'].set_color(TEXT_MAIN); parts['cmedians'].set_linewidth(2)
parts['cbars'].set_color(TEXT_SUB)
parts['cmins'].set_color(TEXT_SUB)
parts['cmaxes'].set_color(TEXT_SUB)
ax.set_xticks(range(1, len(dept_order)+1))
ax.set_xticklabels(dept_order, color=TEXT_MAIN, fontsize=9)
ax.axhline(seuil, color=ACCENT_YLW, linestyle='--', linewidth=1.5, alpha=0.8,
           label=f"Seuil fraude = {seuil:.1f}")
ax.set_title("Score de Risque par Département", color=TEXT_MAIN, fontweight='bold')
ax.set_ylabel("Score de risque", color=TEXT_SUB)
ax.legend(facecolor=CARD_BG, labelcolor=TEXT_MAIN, edgecolor='none', fontsize=9)
ax.tick_params(colors=TEXT_SUB)
for sp in ax.spines.values(): sp.set_visible(False)

# Probabilité de fraude par décile d'ancienneté
ax = axes[0, 1]; ax.set_facecolor(DARK_BG)
df['Anciennete_Decile'] = pd.qcut(df['Anciennete_Annees'], 5,
                                   labels=['1-5 ans', '5-9 ans', '9-13 ans',
                                           '13-18 ans', '18+ ans'])
anc_fraud = df.groupby('Anciennete_Decile', observed=True)['Fraude_Interne'].mean() * 100
col_grad = [ACCENT_BLU, ACCENT_BLU, ACCENT_YLW, ACCENT_RED, ACCENT_RED]
bars = ax.bar(anc_fraud.index, anc_fraud.values, color=col_grad, edgecolor='none', width=0.6)
for bar, v in zip(bars, anc_fraud.values):
    ax.text(bar.get_x() + bar.get_width()/2, v + 0.2,
            f'{v:.1f}%', ha='center', va='bottom', fontsize=10, color=TEXT_MAIN, fontweight='bold')
ax.set_title("Taux de Fraude par Tranche d'Ancienneté", color=TEXT_MAIN, fontweight='bold')
ax.set_xlabel("Ancienneté", color=TEXT_SUB)
ax.set_ylabel("Taux de fraude (%)", color=TEXT_SUB)
ax.tick_params(colors=TEXT_SUB, labelsize=9)
for sp in ax.spines.values(): sp.set_visible(False)

# Top 50 employés à risque
ax = axes[1, 0]; ax.set_facecolor(DARK_BG)
df['Prob_Fraude_RF'] = rf.predict_proba(df[features])[:, 1]
top50 = df.nlargest(50, 'Prob_Fraude_RF')
scatter_col = [ACCENT_RED if f == 1 else ACCENT_YLW
               for f in top50['Fraude_Interne']]
ax.scatter(range(50), top50['Prob_Fraude_RF'].values,
           c=scatter_col, s=55, zorder=5, edgecolors='none')
ax.fill_between(range(50), top50['Prob_Fraude_RF'].values,
                alpha=0.15, color=ACCENT_RED)
ax.axhline(0.5, color=TEXT_SUB, linestyle='--', linewidth=1, alpha=0.6)
legend_elem = [
    mpatches.Patch(facecolor=ACCENT_RED,  label='Fraudeur Confirmé'),
    mpatches.Patch(facecolor=ACCENT_YLW,  label='Suspect Non Identifié'),
]
ax.legend(handles=legend_elem, facecolor=CARD_BG,
           labelcolor=TEXT_MAIN, edgecolor='none', fontsize=9)
ax.set_title("Top 50 Profils à Haut Risque (RF)", color=TEXT_MAIN, fontweight='bold')
ax.set_xlabel("Rang", color=TEXT_SUB)
ax.set_ylabel("Probabilité de Fraude", color=TEXT_SUB)
ax.tick_params(colors=TEXT_SUB)
for sp in ax.spines.values(): sp.set_visible(False)

# Heatmap risque Département × Accès
ax = axes[1, 1]; ax.set_facecolor(DARK_BG)
pivot = df.pivot_table(values='Fraude_Interne', index='Departement',
                        columns='Acces_Privilegie', aggfunc='mean') * 100
pivot.columns = ['Sans Accès Priv.', 'Avec Accès Priv.']
cmap_heat = sns.light_palette(ACCENT_RED, as_cmap=True)
sns.heatmap(pivot, annot=True, fmt='.1f', ax=ax, cmap=cmap_heat,
            linewidths=1.5, linecolor=DARK_BG,
            annot_kws={'size': 12, 'weight': 'bold', 'color': DARK_BG},
            cbar_kws={'label': 'Taux de fraude (%)'})
ax.set_title("Taux de Fraude (%) — Département × Accès Privilégié",
             color=TEXT_MAIN, fontweight='bold')
ax.set_ylabel("Département", color=TEXT_SUB)
ax.set_xlabel("", color=TEXT_SUB)
ax.tick_params(colors=TEXT_SUB, labelsize=9)

plt.tight_layout()
plt.savefig('fig4_risk.png', dpi=150, bbox_inches='tight', facecolor=DARK_BG)
plt.show()
print("✅  Figure 4 enregistrée")

# ── CELLULE 8 : Figure 5 — Dashboard Recommandations ────────

fig = plt.figure(figsize=(20, 13), facecolor=DARK_BG)
fig.suptitle("RECOMMANDATIONS DE CONTRÔLE INTERNE & GOUVERNANCE",
             fontsize=18, fontweight='bold', color=TEXT_MAIN, y=1.0)

# Sous-titre ACFE
fig.text(0.5, 0.965,
         "Basé sur l'ACFE Report to the Nations 2024 — Anti-Fraud Controls",
         ha='center', fontsize=11, color=TEXT_SUB)

gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.5, wspace=0.38,
                       left=0.05, right=0.97, top=0.93, bottom=0.05)

# ── Radar Chart — Facteurs de risque ────────────────────────
ax_radar = fig.add_subplot(gs[0, 0], polar=True)
ax_radar.set_facecolor(DARK_BG)
categories = ['Accès\nPrivilégié', 'Pression\nFinancière',
              'Insatisfaction', 'Ancienneté', 'H.Supp.', 'Congés\nNon Pris']
N = len(categories)
angles = np.linspace(0, 2 * np.pi, N, endpoint=False).tolist()
angles += angles[:1]

# Fraudeurs
fraud_means = [
    df[df['Fraude_Interne'] == 1]['Acces_Privilegie'].mean() * 10,
    df[df['Fraude_Interne'] == 1]['Score_Pression_Financiere'].mean(),
    10 - df[df['Fraude_Interne'] == 1]['Satisfaction_Travail'].mean(),
    df[df['Fraude_Interne'] == 1]['Anciennete_Annees'].mean() / 2.4,
    df[df['Fraude_Interne'] == 1]['Heures_Supp_Mois'].mean() / 5,
    df[df['Fraude_Interne'] == 1]['Conges_Non_Pris'].mean() / 3,
]
# Non-fraudeurs
nfraud_means = [
    df[df['Fraude_Interne'] == 0]['Acces_Privilegie'].mean() * 10,
    df[df['Fraude_Interne'] == 0]['Score_Pression_Financiere'].mean(),
    10 - df[df['Fraude_Interne'] == 0]['Satisfaction_Travail'].mean(),
    df[df['Fraude_Interne'] == 0]['Anciennete_Annees'].mean() / 2.4,
    df[df['Fraude_Interne'] == 0]['Heures_Supp_Mois'].mean() / 5,
    df[df['Fraude_Interne'] == 0]['Conges_Non_Pris'].mean() / 3,
]
fraud_means  += fraud_means[:1]
nfraud_means += nfraud_means[:1]

ax_radar.plot(angles, fraud_means,  color=ACCENT_RED, linewidth=2.5, label='Fraudeur')
ax_radar.fill(angles, fraud_means,  color=ACCENT_RED, alpha=0.25)
ax_radar.plot(angles, nfraud_means, color=ACCENT_BLU, linewidth=2.5, label='Non-Fraudeur')
ax_radar.fill(angles, nfraud_means, color=ACCENT_BLU, alpha=0.15)
ax_radar.set_xticks(angles[:-1])
ax_radar.set_xticklabels(categories, color=TEXT_MAIN, fontsize=8)
ax_radar.tick_params(colors=TEXT_SUB)
ax_radar.set_facecolor(DARK_BG)
ax_radar.spines['polar'].set_color(TEXT_SUB)
ax_radar.yaxis.set_tick_params(labelcolor=TEXT_SUB, labelsize=6)
ax_radar.grid(color=TEXT_SUB, alpha=0.3, linewidth=0.7)
ax_radar.set_title("Profil Radar — Fraudeur vs Non-Fraudeur",
                   color=TEXT_MAIN, fontweight='bold', pad=20)
ax_radar.legend(loc='upper right', bbox_to_anchor=(1.35, 1.1),
                facecolor=CARD_BG, labelcolor=TEXT_MAIN, edgecolor='none', fontsize=9)

# ── Probabilités cumulées ────────────────────────────────────
ax_cum = fig.add_subplot(gs[0, 1])
ax_cum.set_facecolor(DARK_BG)
sorted_probs = np.sort(df['Prob_Fraude_RF'])[::-1]
cum_fraud = np.cumsum(
    df.sort_values('Prob_Fraude_RF', ascending=False)['Fraude_Interne'].values
) / df['Fraude_Interne'].sum() * 100
pop_pct = np.arange(1, len(df)+1) / len(df) * 100
ax_cum.plot(pop_pct, cum_fraud, color=ACCENT_GRN, linewidth=2.5,
            label='Modèle RF')
ax_cum.plot([0, 100], [0, 100], '--', color=TEXT_SUB,
            linewidth=1.5, alpha=0.6, label='Modèle Aléatoire')
ax_cum.fill_between(pop_pct, cum_fraud, pop_pct,
                    alpha=0.12, color=ACCENT_GRN)
ax_cum.axvline(20, color=ACCENT_YLW, linestyle=':', linewidth=1.5)
idx_20 = np.searchsorted(pop_pct, 20)
ax_cum.annotate(f"Top 20% pop.\n→ {cum_fraud[idx_20]:.0f}% fraudes",
                xy=(20, cum_fraud[idx_20]),
                xytext=(35, cum_fraud[idx_20] - 15),
                color=ACCENT_YLW, fontsize=8.5,
                arrowprops=dict(arrowstyle='->', color=ACCENT_YLW, lw=1.5))
ax_cum.set_title("Courbe de Gain Cumulé", color=TEXT_MAIN, fontweight='bold')
ax_cum.set_xlabel("% Population Auditée", color=TEXT_SUB)
ax_cum.set_ylabel("% Fraudes Détectées", color=TEXT_SUB)
ax_cum.legend(facecolor=CARD_BG, labelcolor=TEXT_MAIN, edgecolor='none', fontsize=9)
ax_cum.tick_params(colors=TEXT_SUB)
for sp in ax_cum.spines.values(): sp.set_visible(False)

# ── Matrice de Risque 2×2 ────────────────────────────────────
ax_mat = fig.add_subplot(gs[0, 2])
ax_mat.set_facecolor(DARK_BG); ax_mat.axis('off')
ax_mat.set_xlim(0, 10); ax_mat.set_ylim(0, 10)
ax_mat.set_title("Matrice Risque — Priorité d'Audit",
                 color=TEXT_MAIN, fontweight='bold', pad=10)

quadrants = [
    (0.3, 5.3, 4.4, 4.4, "#2d4a2d", "SURVEILLANCE\nROUTINIÈRE", "Accès limité\nFaible pression",    "#2EC4B6"),
    (5.3, 5.3, 4.4, 4.4, "#4a3d1a", "SURVEILLANCE\nACCRUE",     "Fort accès\nFaible pression",       ACCENT_YLW),
    (0.3, 0.3, 4.4, 4.4, "#3d2820", "AUDIT\nPRIORITAIRE",       "Accès limité\nForte pression",      ACCENT_YLW),
    (5.3, 0.3, 4.4, 4.4, "#5a1a1a", "⚠️ RISQUE\nCRITIQUE",      "Fort accès + Forte pression\n→ Audit immédiat", ACCENT_RED),
]
for x, y, w, h, bg, title, sub, col in quadrants:
    rect = FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.1",
                          facecolor=bg, edgecolor=col, linewidth=2)
    ax_mat.add_patch(rect)
    ax_mat.text(x + w/2, y + h*0.62, title, ha='center', va='center',
                fontsize=9, fontweight='bold', color=col)
    ax_mat.text(x + w/2, y + h*0.25, sub, ha='center', va='center',
                fontsize=7.5, color=TEXT_SUB, linespacing=1.4)

ax_mat.text(5, -0.4, "→ ACCÈS PRIVILÉGIÉ", ha='center', color=TEXT_SUB, fontsize=9)
ax_mat.text(-0.3, 5, "↑ PRESSION\nFINANCIÈRE", ha='center', va='center',
            color=TEXT_SUB, fontsize=9, rotation=90)

# ── 6 Recommandations ────────────────────────────────────────
reco_data = [
    (gs[1, 0], "1. CONTRÔLE DES ACCÈS",
     ["• Revue semestrielle des accès privilégiés",
      "• Principe du moindre privilège (PoLP)",
      "• Journalisation & alertes en temps réel",
      "• Séparation des tâches (SoD) obligatoire"],
     ACCENT_GRN, "🔐"),
    (gs[1, 1], "2. PROGRAMME DE PRÉVENTION",
     ["• Hotline fraude anonyme (réduction ~25%)*",
      "• Formation anti-fraude annuelle obligatoire",
      "• Politique de rotation des postes sensibles",
      "• Audit surprise trimestriel (Achats/Finance)"],
     ACCENT_YLW, "🛡️"),
    (gs[1, 2], "3. DÉTECTION PRÉCOCE",
     ["• Déploiement du modèle RF en production",
      "• Score de risque recalculé chaque mois",
      "• Tableau de bord RH — signaux comportementaux",
      "• Revue des top 5% de profils à risque"],
     ACCENT_RED, "🔍"),
]
for gs_pos, title, bullets, col, icon in reco_data:
    ax_r = fig.add_subplot(gs_pos)
    ax_r.set_facecolor(CARD_BG); ax_r.axis('off')
    ax_r.text(0.08, 0.92, icon + "  " + title,
              transform=ax_r.transAxes, fontsize=10, fontweight='bold',
              color=col, va='top')
    for i, b in enumerate(bullets):
        ax_r.text(0.06, 0.75 - i * 0.17, b,
                  transform=ax_r.transAxes, fontsize=9, color=TEXT_MAIN, va='top')
    rect = FancyBboxPatch((0.02, 0.02), 0.96, 0.96,
                          boxstyle="round,pad=0.02",
                          facecolor='none', edgecolor=col,
                          linewidth=1.8, transform=ax_r.transAxes)
    ax_r.add_patch(rect)

fig.text(0.5, 0.01,
         "* ACFE 2024 : organisations avec hotline détectent la fraude 50% plus vite et subissent des pertes médians 20% inférieures.",
         ha='center', fontsize=8.5, color=TEXT_SUB, style='italic')

plt.savefig('fig5_recommendations.png', dpi=150, bbox_inches='tight',
            facecolor=DARK_BG)
plt.show()
print("✅  Figure 5 enregistrée")

# ── CELLULE 9 : Synthèse finale ──────────────────────────────

print("\n" + "═"*65)
print("  SYNTHÈSE — PRÉDICTION DE FRAUDE INTERNE")
print("═"*65)

best_model = max(models_perf.items(), key=lambda x: x[1][2])
print(f"\n  🏆  Meilleur modèle : {best_model[0]}")
print(f"      AUC (CV-5)     : {best_model[1][2]:.4f}")

top_feat_idx = np.argsort(rf.feature_importances_)[::-1]
print(f"\n  📌  Variables les plus prédictives :")
for i in top_feat_idx[:3]:
    print(f"      → {feat_labels[i]:<25} ({rf.feature_importances_[i]:.3f})")

dept_stats2 = df.groupby('Departement').agg(
    total=('Fraude_Interne', 'count'),
    fraudes=('Fraude_Interne', 'sum')
).reset_index()
dept_stats2['taux'] = dept_stats2['fraudes'] / dept_stats2['total'] * 100
risky_depts = dept_stats2.nlargest(2, 'taux')
print(f"\n  ⚠️   Départements prioritaires :")
for _, row in risky_depts.iterrows():
    print(f"      → {row['Departement']:<15} taux = {row['taux']:.1f}%")

top10 = df.nlargest(10, 'Prob_Fraude_RF')[
    ['ID_Employe', 'Departement', 'Anciennete_Annees',
     'Acces_Privilegie', 'Score_Pression_Financiere',
     'Prob_Fraude_RF', 'Fraude_Interne']
].rename(columns={'Prob_Fraude_RF': 'Prob_RF'})

print(f"\n  🔍  Top 10 profils à risque maximal :\n")
print(top10.to_string(index=False, float_format='{:.3f}'.format))
print("\n" + "═"*65)
print("  Figures sauvegardées : fig1_overview.png … fig5_recommendations.png")
print("═"*65)